### ISSUE TITLE
`'ng-template' is not a known element:`

### ISSUE THREAD

**Issue by pangky24** [softsimon/angular-2-dropdown-multiselect#117] opened 2017-03-30 09:31 UTC
Thanks you for making this great module~ :)

I have installed 2 or 3 weeks ago and had no problem to use until reinstalling it today.
And it is making some error below.
> error
`zone.js:388 Unhandled Promise rejection: Template parse errors:`
`'ng-template' is not a known element:`

and I check the issue below.
https://github.com/softsimon/angular-2-dropdown-multiselect/issues/84

but, you know I am using angular2.4.0 and I just need fixed-version
and I don't want to upgrade angular4.0.
so, how can I get the fixed version below?

> multiselect-dropdown.ts
`
          <ng-template [ngIf]="option.isLabel">
            {{ option.name }}
          </ng-template>
`
=> 
> want to get version
`
          <template [ngIf]="option.isLabel">
            {{ option.name }}
          </template>
`

current version.
> "angular-2-dropdown-multiselect": "^1.0.6",

**Comment by pangky24** [comment] 2017-03-30 09:50
ooops...

release 1.6 has fixed yesterday..;;;;

How I try to solve this problem?
Please, give me an answer;;;;;

> template -> ng-template

> https://github.com/softsimon/angular-2-dropdown-multiselect/commit/f6931c9a37a7029d435a6d7da633010d36578623

**Comment by softsimon** [comment] 2017-03-30 10:05
The latest release requires angular 4.0 or later since <ng-template is 4.x only. Since this causes issues for 2.x users I will revert that change so 2.x still works again.

Wait for next release or upgrade to latest stable angular 4.0.

**Comment by mrgle** [comment] 2017-03-30 17:52
ran into this issue as well. by default when you use npm to add the dependency it uses ^ notation and a second installation pulled down 1.0.6 instead of the 1.0.2 I was previously using.

Now that angular is moving the semantic versioning please consider doing the same for your project to prevent unintended breakage.

**Comment by tmsuresh5** [comment] 2017-03-31 14:58
Guys,
Did you resolve an issue some how, since me too got the same exception in my project, just i installed "angular-2-dropdown multiselect" today and the version is "1.0.6" angular version is "2.4.0" and got the below exception .. any idea how to resolve, based on above thread it should be resolved by 1.0.6 version on yesterday itself, but not yet. Any quick help will be appreciated !! Thanks.

'ng-template' is not a known element:
1. If 'ng-template' is an Angular component, then verify that it is part of this module.
2. If 'ng-template' is a Web Component then add "CUSTOM_ELEMENTS_SCHEMA" to the '@NgModule.schemas' of this component to suppress this message. ("!option.isLabel && setSelected($event, option)" [class.dropdown-header]="option.isLabel">
          [ERROR ->]<ng-template [ngIf]="option.isLabel">
            {{ option.name }}
          </ng-template>

**Comment by mrgle** [comment] 2017-03-31 15:06
@tmsuresh5 change the version of the library use to a previous version. Personally I changed to excplicitly use 1.0.2 since that was working for me previously, but newer versions that aren't 1.0.6 might also work.

**Comment by tmsuresh5** [comment] 2017-03-31 15:54
Thanks for your input and i did the version 1.0.2 the above exception is not coming, but got the below exception any idea??
Now the drop down is displaying but with one value("option 1") even "Option 2 is there per example given by the site.

EXCEPTION: Error in ./MultiselectDropdown class MultiselectDropdown - inline template:30:30 caused by: Cannot set property style of [object Object] which has only a getter

**Comment by pangky24** [comment] 2017-04-04 08:43
@softsimon @mrgle Thanks ~~

**Closed** 2017-04-04 08:44 UTC

**Comment by Jamunadevi-Vijayan** [comment] 2017-05-05 13:30
Getting the below error when using angular-2-dropdown-multiselect: 1.2.0 and @angular : 2.4.10

polyfills.bundle.js:6641 Unhandled Promise rejection: Template parse errors:
'ng-template' is not a known element:
1. If 'ng-template' is an Angular component, then verify that it is part of this module.
2. If 'ng-template' is a Web Component then add "CUSTOM_ELEMENTS_SCHEMA" to the '@NgModule.schemas' of this component to suppress this message. ("" (click)="!option.isLabel && setSelected($event, option)" [class.dropdown-header]="option.isLabel">[ERROR ->]<ng-template [ngIf]="option.isLabel">{{ option.name }}</ng-template><a *ngIf="!option.isLabel" href=""): MultiselectDropdown@0:2195 ; Zone: <root> ; Task: Promise.then ; Value: SyntaxError__zone_symbol__currentTask: ZoneTask__zone_symbol__error: Error: Template parse errors:
'ng-template' is not a known element:
1. If 'ng-template' is an Angular component, then verify that it is part of this module.
2. If 'ng-template' is a Web Component then add "CUSTOM_ELEMENTS_SCHEMA" to the '@NgModule.schemas' of this component to suppress this message. ("" (click)="!option.isLabel && setSelected($event, option)" [class.dropdown-header]="option.isLabel">[ERROR ->]<ng-template [ngIf]="option.isLabel">{{ option.name }}</ng-template><a *ngIf="!option.isLabel" href=""): MultiselectDropdown@0:2195
    at SyntaxError.ZoneAwareError (http://localhost:4200/polyfills.bundle.js:7111:33)
    at SyntaxError.BaseError [as constructor] (http://localhost:4200/vendor.bundle.js:101117:16)
    at new SyntaxError (http://localhost:4200/vendor.bundle.js:12269:16)
    at TemplateParser.parse (http://localhost:4200/vendor.bundle.js:32850:19)
    at JitCompiler._compileTemplate (http://localhost:4200/vendor.bundle.js:73323:68)
    at http://localhost:4200/vendor.bundle.js:73206:62
    at Set.forEach (native)
    at JitCompiler._compileComponents (http://localhost:4200/vendor.bundle.js:73206:19)
    at createResult (http://localhost:4200/vendor.bundle.js:73088:19)
    at ZoneDelegate.invoke (http://localhost:4200/polyfills.bundle.js:6453:26)
    at Zone.run (http://localhost:4200/polyfills.bundle.js:6245:43)
    at http://localhost:4200/polyfills.bundle.js:6832:57
    at ZoneDelegate.invokeTask (http://localhost:4200/polyfills.bundle.js:6486:31)
    at Zone.runTask (http://localhost:4200/polyfills.bundle.js:6285:47)
    at drainMicroTaskQueue (http://localhost:4200/polyfills.bundle.js:6665:35)__zone_symbol__message: "Template parse errors:↵'ng-template' is not a known element:↵1. If 'ng-template' is an Angular component, then verify that it is part of this module.↵2. If 'ng-template' is a Web Component then add "CUSTOM_ELEMENTS_SCHEMA" to the '@NgModule.schemas' of this component to suppress this message. ("" (click)="!option.isLabel && setSelected($event, option)" [class.dropdown-header]="option.isLabel">[ERROR ->]<ng-template [ngIf]="option.isLabel">{{ option.name }}</ng-template><a *ngIf="!option.isLabel" href=""): MultiselectDropdown@0:2195"__zone_symbol__stack: "Error: Template parse errors:↵'ng-template' is not a known element:↵1. If 'ng-template' is an Angular component, then verify that it is part of this module.↵2. If 'ng-template' is a Web Component then add "CUSTOM_ELEMENTS_SCHEMA" to the '@NgModule.schemas' of this component to suppress this message. ("" (click)="!option.isLabel && setSelected($event, option)" [class.dropdown-header]="option.isLabel">[ERROR ->]<ng-template [ngIf]="option.isLabel">{{ option.name }}</ng-template><a *ngIf="!option.isLabel" href=""): MultiselectDropdown@0:2195↵    at SyntaxError.ZoneAwareError (http://localhost:4200/polyfills.bundle.js:7111:33)↵    at SyntaxError.BaseError [as constructor] (http://localhost:4200/vendor.bundle.js:101117:16)↵    at new SyntaxError (http://localhost:4200/vendor.bundle.js:12269:16)↵    at TemplateParser.parse (http://localhost:4200/vendor.bundle.js:32850:19)↵    at JitCompiler._compileTemplate (http://localhost:4200/vendor.bundle.js:73323:68)↵    at http://localhost:4200/vendor.bundle.js:73206:62↵    at Set.forEach (native)↵    at JitCompiler._compileComponents (http://localhost:4200/vendor.bundle.js:73206:19)↵    at createResult (http://localhost:4200/vendor.bundle.js:73088:19)↵    at ZoneDelegate.invoke (http://localhost:4200/polyfills.bundle.js:6453:26)↵    at Zone.run (http://localhost:4200/polyfills.bundle.js:6245:43)↵    at http://localhost:4200/polyfills.bundle.js:6832:57↵    at ZoneDelegate.invokeTask (http://localhost:4200/polyfills.bundle.js:6486:31)↵    at Zone.runTask (http://localhost:4200/polyfills.bundle.js:6285:47)↵    at drainMicroTaskQueue (http://localhost:4200/polyfills.bundle.js:6665:35)"_nativeError: ZoneAwareErrormessage: (...)get message: ()set message: (value)name: (...)get name: ()set name: (value)originalStack: (...)get originalStack: ()set originalStack: (value)stack: (...)get stack: ()set stack: (value)toSource: ()toString: ()zoneAwareStack: (...)get zoneAwareStack: ()set zoneAwareStack: (value)__proto__: BaseError Error: Template parse errors:
'ng-template' is not a known element:
1. If 'ng-template' is an Angular component, then verify that it is part of this module.
2. If 'ng-template' is a Web Component then add "CUSTOM_ELEMENTS_SCHEMA" to the '@NgModule.schemas' of this component to suppress this message. ("" (click)="!option.isLabel && setSelected($event, option)" [class.dropdown-header]="option.isLabel">[ERROR ->]<ng-template [ngIf]="option.isLabel">{{ option.name }}</ng-template><a *ngIf="!option.isLabel" href=""): MultiselectDropdown@0:2195
    at SyntaxError.ZoneAwareError (http://localhost:4200/polyfills.bundle.js:7111:33)
    at SyntaxError.BaseError [as constructor] (http://localhost:4200/vendor.bundle.js:101117:16)
    at new SyntaxError (http://localhost:4200/vendor.bundle.js:12269:16)
    at TemplateParser.parse (http://localhost:4200/vendor.bundle.js:32850:19)
    at JitCompiler._compileTemplate (http://localhost:4200/vendor.bundle.js:73323:68)
    at http://localhost:4200/vendor.bundle.js:73206:62
    at Set.forEach (native)
    at JitCompiler._compileComponents (http://localhost:4200/vendor.bundle.js:73206:19)
    at createResult (http://localhost:4200/vendor.bundle.js:73088:19)
    at ZoneDelegate.invoke (http://localhost:4200/polyfills.bundle.js:6453:26)
    at Zone.run (http://localhost:4200/polyfills.bundle.js:6245:43)
    at http://localhost:4200/polyfills.bundle.js:6832:57
    at ZoneDelegate.invokeTask (http://localhost:4200/polyfills.bundle.js:6486:31)
    at Zone.runTask (http://localhost:4200/polyfills.bundle.js:6285:47)
    at drainMicroTaskQueue (http://localhost:4200/polyfills.bundle.js:6665:35)
consoleError @ polyfills.bundle.js:6641

**Comment by softsimon** [comment] 2017-05-05 13:31
@Jamunadevi-Vijayan Upgrade to Angular 4.x
