### ISSUE TITLE
setting options on reload

### ISSUE THREAD

**Issue by mkteagle** [softsimon/angular-2-dropdown-multiselect#143] opened 2017-04-21 19:06 UTC
I am trying to implement localStorage and to automatically select the options when I refresh the browser. I am not having any luck. Does anyone have pointers. Right now it will only set them after I select something and than it will refresh and set the modal with what is in localStorage.

**Comment by chris--jones** [comment] 2017-04-21 23:39
A sample of your code would help, but if you're trying to change the value of your options array it won't trigger change detection unless the reference changes. 
Try to assign the options to a new array e.g. Using map or slice rather than pushing the missing elements onto an existing array.

**Comment by nicholasguyett** [comment] 2017-04-24 16:35
Yeah.  This is not a bug specific to this component.  Going to close it to keep the issues list clean, but feel free to continue the conversation.

**Closed by nicholasguyett** 2017-04-24 16:35 UTC
