### ISSUE TITLE
ids should be any type

### ISSUE THREAD

**Issue by dessalines** [softsimon/angular-2-dropdown-multiselect#39] opened 2016-12-13 19:52 UTC
In html, the `<option value="id">text</option>`, the ID is text, but the `IMultiSelectOption` enforces a numeric id. This would require me to basically make another mapping from those options to values, since I need string values for my options.

**Comment by nicholasguyett** [comment] 2016-12-13 20:38
Duplicate of #8.

**Closed by nicholasguyett** 2016-12-13 20:38 UTC
Labels: enhancement
