### ISSUE TITLE
How can we close the dropdown when someone click other than dropdown box?

### ISSUE THREAD

**Issue by sudhirroy-tudip** [softsimon/angular-2-dropdown-multiselect#82] opened 2017-02-27 22:21 UTC
Actually I am using this component in ng2-modal. I have 2 multi dropdown component in modal. I used isVisible assignment that accept boolean value for open and close. But, I am struck to how I close if someone click in modal background. If I use this click event then multi dropdown is also in that modal. So, if I click dropdown content then it automatically fire modal click event. How we handle this? 
By simple meaning, I want focusout event to close the dropdown?

**Comment by softsimon** [comment] 2017-02-27 22:40
Could you try edit the code in the multiselect-dropdown.ts into this and try if it works. Changed rows are in bold.

`
@HostListener('document: click', **['$event',** '$event.target'])
  onClick(**event: Event,** target: HTMLElement) {
    let parentFound = false;
    while (target != null && !parentFound) {
      if (target === this.element.nativeElement) {
        parentFound = true;
      }
      target = target.parentElement;
    }
    if (!parentFound) {
      **event.stopPropagation();**
      this.isVisible = false;
      this.dropdownClosed.emit();
    }
  }
`

**Comment by sudhirroy-tudip** [comment] 2017-03-02 15:20
I did it, it works for me when I implement it in a page but when I put it in modal (ng2-modal), it still not working. Can you help me. I think if it have focus out event so anyone who click out of this component, it automatically close out.

**Comment by chris--jones** [comment] 2017-04-14 05:14
Is this a duplicate of #70 ?

I've yet to attempt reproducing this issue with ng2-modal, however the div with class "dropdown" rendered within the component is a block element meaning it will fill the horizontal space (I have highlighted this space in yellow below), so clicking in this space will not close the dropdown:

![image](https://cloud.githubusercontent.com/assets/10459377/25033824/9a1a2ca0-2124-11e7-9cfa-5d91db8f54d8.png)

Perhaps this should be ```display: inline-block```

**Comment by chris--jones** [comment] 2017-04-25 05:34
Closing this as duplicate of #70

**Closed by chris--jones** 2017-04-25 05:34 UTC
Labels: duplicate
